version: "2"
services:

  detector:
    build: .
    container_name: detector
    hostname: detector 
    volumes:
      - ./:/root/dev
    ports:
      - "80:80"
      - "32:22"    
    working_dir: /root/dev
    command: bash -c "./init-script.sh"
