version: "2"
services:

  db:
    image: postgres
    container_name: dlib_db
    expose:
      - "5432"

  web:
    build: .
    container_name: dlib
    hostname: dlib
    volumes:
      - ./:/root/shared
    ports:
      - "2222:22"
    working_dir: /root/shared
    command: bash -c "./init-script.sh"
    links:
      - db
